package com.pahana.edu.billing.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class Bill {
    private int id;                      // PK
    private int customerId;              // FK -> customers.id
    private double totalAmount;          // sum of line totals (before discount)
    private double discountPercent;      // 0..100
    private double netAmount;            // total - (total * discount/100)
    private LocalDateTime createdAt;     // generated by DB (can be null before insert)

    // Optional: convenience list when loading a bill with its items
    private List<BillItem> items = new ArrayList<>();

    // Getters & Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public int getCustomerId() { return customerId; }
    public void setCustomerId(int customerId) { this.customerId = customerId; }

    public double getTotalAmount() { return totalAmount; }
    public void setTotalAmount(double totalAmount) { this.totalAmount = totalAmount; }

    public double getDiscountPercent() { return discountPercent; }
    public void setDiscountPercent(double discountPercent) { this.discountPercent = discountPercent; }

    public double getNetAmount() { return netAmount; }
    public void setNetAmount(double netAmount) { this.netAmount = netAmount; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public List<BillItem> getItems() { return items; }
    public void setItems(List<BillItem> items) { this.items = items; }

    // Helper: recompute totals from current items list
    public void recomputeTotals() {
        double total = 0.0;
        for (BillItem bi : items) total += bi.getLineTotal();
        this.totalAmount = total;
        this.netAmount = Math.round((total - (total * (discountPercent / 100.0))) * 100.0) / 100.0;
    }
}
